# Generated by Django 3.1.6 on 2021-02-18 11:20

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=33), blank=True, null=True, size=None)),
                ('admins', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=33), size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown', models.IntegerField(default=10)),
                ('admins_timestamp', models.DateTimeField(default=datetime.datetime(2021, 2, 18, 11, 20, 20, 730818))),
                ('list_timestamp', models.DateTimeField(default=datetime.datetime(2021, 2, 18, 11, 20, 20, 730846))),
                ('message_id', models.IntegerField()),
            ],
        ),
    ]
