# Generated by Django 3.1.6 on 2021-02-18 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='admins_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 11, 39, 33, 12665, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='queue',
            name='list_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 11, 39, 33, 12699, tzinfo=utc)),
        ),
    ]
