# Generated by Django 3.1.6 on 2021-02-18 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210218_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='admins_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 11, 54, 40, 223370, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='queue',
            name='list_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 11, 54, 40, 223403, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='queue',
            name='message_id',
            field=models.IntegerField(default=0),
        ),
    ]
